/**
 * Auto-generated by effect-bundler.
 * This file is created on startup and automatically updated when routes change
 * for all programs that use FileRouter.layer.
 */

const layout_ = {
  path: "/",
  parent: undefined,
  load: () => import("./_layout.tsx"),
}

const page_ = {
  path: "/",
  parent: layout_,
  load: () => import("./_page.tsx"),
}

const layout_about = {
  path: "/about",
  parent: layout_,
  load: () => import("./about/_layout.tsx"),
}

const page_about = {
  path: "/about",
  parent: layout_about,
  load: () => import("./about/_page.tsx"),
}

const page_events = {
  path: "/events",
  parent: layout_,
  load: () => import("./events/_page.tsx"),
}

export const Pages = [
  page_,
  page_about,
  page_events,
] as const

