/** 
 * Auto-generated by effect-bundler.
 */

import type { Router } from "effect-bundler"

const layout__ = {
  path: "/",
  load: () => import("./_layout.tsx"),
} as const

const page__ = {
  path: "/",
  parent: layout__,
  load: () => import("./_page.tsx"),
} as const

const layout__about = {
  path: "/about",
  parent: layout__,
  load: () => import("./about/_layout.tsx"),
} as const

const page__about = {
  path: "/about",
  parent: layout__about,
  load: () => import("./about/_page.tsx"),
} as const

const server__events_json = {
  path: "/events.json",
  load: () => import("./events.json/_server.ts"),
} as const

export const Layouts: Router.LayoutRoutes = [
  layout__,
  layout__about
] as const

export const Pages: Router.PageRoutes = [
  page__,
  page__about
] as const

export const Servers: Router.ServerRoutes = [
  server__events_json
] as const
 